# Generated by Django 3.1.7 on 2021-04-05 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, null=True, verbose_name='عنوان')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('price', models.IntegerField(default=0, null=True, verbose_name='قیمت')),
                ('state', models.CharField(choices=[('P', 'در حال انتظار'), ('A', 'مورد قبول'), ('R', 'عدم تایید')], default='P', max_length=1, null=True, verbose_name='وضعیت')),
                ('DateCreated', django_jalali.db.models.jDateTimeField(null=True, verbose_name='زمان ایجاد')),
                ('file', models.FileField(blank=True, null=True, upload_to='blog/files/', verbose_name='فایل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images/', verbose_name='عکس')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ\u200cها',
                'ordering': ('title', '-price'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت\u200cها',
            },
        ),
    ]
