# Generated by Django 3.1.7 on 2021-04-02 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20210402_1804'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'بلاگ', 'verbose_name_plural': 'بلاگ\u200cها'},
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='state',
            field=models.CharField(choices=[('P', 'در حال انتظار'), ('A', 'مورد قبول'), ('R', 'عدم تایید')], default='P', max_length=1, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=120, null=True, verbose_name='عنوان'),
        ),
    ]
