# Generated by Django 3.1.7 on 2021-04-03 05:35

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blog_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='DateCreated',
            field=django_jalali.db.models.jDateTimeField(null=True, verbose_name='زمان ایجاد'),
        ),
    ]
