# Generated by Django 3.1.7 on 2021-04-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210403_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
